/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import javax.swing.table.DefaultTableModel;
import metodosnumericos.Conversiones;
import metodosnumericos.Errores;
import metodosnumericos.PuntoFlotante;
import metodosnumericos.proErrores;
import metodosnumericos.Biseccion;
import metodosnumericos.Bolzano;
import metodosnumericos.Graficador;
import metodosnumericos.EspMetricos;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metodosnumericos.GenPDF;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author pablo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel modelo;
    Conversiones Conver = new Conversiones();
    Errores Erro = new Errores();
    PuntoFlotante PuntoF = new PuntoFlotante();
    proErrores proErro = new proErrores();
    Biseccion Bisec = new Biseccion();
    Bolzano Bolza = new Bolzano();
    Graficador Graf = new Graficador();
    EspMetricos Esp = new EspMetricos();
    GenPDF generar = new GenPDF();

    public Main() {
        initComponents();
        LimpiarConver();
        LimpiarErr();
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Titulo_Principal = new javax.swing.JLabel();
        Unidades = new javax.swing.JTabbedPane();
        Unidad1 = new javax.swing.JTabbedPane();
        Conversiones = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        ComboBox_CW = new javax.swing.JComboBox<>();
        cajaTxt_CW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        ComboBox_CT = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        labelTxtResConv = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PanErrores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaTxtErrN1 = new javax.swing.JTextField();
        cajaTxtErrN2 = new javax.swing.JTextField();
        btErrAbs = new javax.swing.JButton();
        btErrRe = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtResEa = new javax.swing.JLabel();
        txtResEr = new javax.swing.JLabel();
        btLimErr = new javax.swing.JButton();
        PunFlotante = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cajaTxtPfijoYflota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btPflota = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtResSigno = new javax.swing.JLabel();
        txtResExBin = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtResMan = new javax.swing.JLabel();
        txtResValDeci = new javax.swing.JLabel();
        txtPfloatBin = new javax.swing.JLabel();
        txtPfloatHexa = new javax.swing.JLabel();
        txtResPfloatBin = new javax.swing.JLabel();
        txtResPfloatHexa = new javax.swing.JLabel();
        btLimPuntoFloat = new javax.swing.JButton();
        GenPDFPuntoFyF = new javax.swing.JButton();
        PropaErrores = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cajaTxtValorProX = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cajaTxtNumIterPro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProErro = new javax.swing.JTable();
        btCalcularProErro = new javax.swing.JButton();
        btLimpiarProErro = new javax.swing.JButton();
        Bolzano = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cajaTxtInterA = new javax.swing.JTextField();
        cajaTxtInterB = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        M_Bolzano = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cajaTxtFuncion = new javax.swing.JTextField();
        FuncionXD = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        LimpiarMBolza = new javax.swing.JButton();
        Biseccion = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cajaTxtFB = new javax.swing.JTextField();
        cajaTxtBInteA = new javax.swing.JTextField();
        cajaTxtBInteB = new javax.swing.JTextField();
        M_Biseccion = new javax.swing.JButton();
        Limpiar_MBisec = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        RespuestaMB = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        EspMetricos = new javax.swing.JPanel();
        CalcularEsMetricos = new javax.swing.JButton();
        Limpiar_Espacios = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        cajaTxt_x1 = new javax.swing.JTextField();
        cajaTxt_y1 = new javax.swing.JTextField();
        cajaTxt_x2 = new javax.swing.JTextField();
        cajaTxt_y2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Respuesta_Esp = new javax.swing.JLabel();
        SerieTylor = new javax.swing.JPanel();
        Unidad2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(23, 102, 110));

        Titulo_Principal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Titulo_Principal.setForeground(new java.awt.Color(36, 162, 173));
        Titulo_Principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_Principal.setText("METODOS NÚMERICOS");

        Conversiones.setBackground(new java.awt.Color(34, 96, 110));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(146, 223, 240));
        jLabel43.setText("INGRESE EL NUMERO A CONVERTIR:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(146, 223, 240));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("CONVERSIONES");

        ComboBox_CW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binario", "Hexadecimal", "Octal" }));
        ComboBox_CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CWActionPerformed(evt);
            }
        });

        jButton1.setText("CONVERTIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(146, 223, 240));
        jLabel46.setText("EL NUMERO A CONVERTIDO ES :");

        ComboBox_CT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binario", "Hexadecimal", "Octal" }));
        ComboBox_CT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CTActionPerformed(evt);
            }
        });

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        labelTxtResConv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTxtResConv.setForeground(new java.awt.Color(146, 223, 240));
        labelTxtResConv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTxtResConv.setText("--");

        jButton2.setText("CONVERTIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConversionesLayout = new javax.swing.GroupLayout(Conversiones);
        Conversiones.setLayout(ConversionesLayout);
        ConversionesLayout.setHorizontalGroup(
            ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConversionesLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95))
            .addGroup(ConversionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaTxt_CW, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(labelTxtResConv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_CW, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox_CT, 0, 133, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConversionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        ConversionesLayout.setVerticalGroup(
            ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversionesLayout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cajaTxt_CW, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(ComboBox_CW, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTxtResConv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ComboBox_CT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(292, 292, 292))
        );

        Unidad1.addTab("CONVERSIONES", Conversiones);

        PanErrores.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ERRORES");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NUMERO 2:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NUMERO 1:");

        btErrAbs.setBackground(new java.awt.Color(153, 255, 204));
        btErrAbs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btErrAbs.setText("ERROR ABSOLUTO");
        btErrAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrAbsActionPerformed(evt);
            }
        });

        btErrRe.setBackground(new java.awt.Color(153, 255, 204));
        btErrRe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btErrRe.setText("ERROR RELATIVO");
        btErrRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErrReActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("RESULTADOS:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ERROR ABSOLUTO:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ERROR RELATIVO:");

        txtResEa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEa.setText("--");

        txtResEr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtResEr.setText("--");

        btLimErr.setBackground(new java.awt.Color(153, 255, 204));
        btLimErr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimErr.setText("LIMPIAR");
        btLimErr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimErrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanErroresLayout = new javax.swing.GroupLayout(PanErrores);
        PanErrores.setLayout(PanErroresLayout);
        PanErroresLayout.setHorizontalGroup(
            PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanErroresLayout.createSequentialGroup()
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanErroresLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(btErrAbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(btErrRe, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanErroresLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cajaTxtErrN2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                                    .addGroup(PanErroresLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cajaTxtErrN1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                                .addGap(14, 14, 14)))
                        .addGap(34, 34, 34))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResEa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addGap(149, 149, 149))
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResEr, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanErroresLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btLimErr, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(133, 133, 133))
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(133, 133, 133)))
                .addGap(173, 173, 173))
        );
        PanErroresLayout.setVerticalGroup(
            PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanErroresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addComponent(cajaTxtErrN1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cajaTxtErrN2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btErrAbs, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btErrRe, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btLimErr, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(PanErroresLayout.createSequentialGroup()
                        .addComponent(txtResEa, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGroup(PanErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtResEr, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );

        Unidad1.addTab("ERRORES", PanErrores);

        PunFlotante.setBackground(new java.awt.Color(255, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("PUNTO FIJO Y FLOTANTE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Ingresa el valor:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("RESPUESTAS:");

        btPflota.setBackground(new java.awt.Color(255, 102, 102));
        btPflota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPflota.setText("CALCULAR");
        btPflota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPflotaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("SIGNO:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("EXPONENTE (BINARIO):");

        txtResSigno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResSigno.setText("--");

        txtResExBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResExBin.setText("--");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("MANTIZA (BINARIO):");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("VALOR DECIMAL:");

        txtResMan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResMan.setText("--");

        txtResValDeci.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResValDeci.setText("--");

        txtPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatBin.setText("VALOR BINARIO:");

        txtPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPfloatHexa.setText("VALOR HEXADECIMAL:");

        txtResPfloatBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatBin.setText("--");

        txtResPfloatHexa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResPfloatHexa.setText("--");

        btLimPuntoFloat.setBackground(new java.awt.Color(255, 102, 102));
        btLimPuntoFloat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimPuntoFloat.setText("LIMPIAR");
        btLimPuntoFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimPuntoFloatActionPerformed(evt);
            }
        });

        GenPDFPuntoFyF.setBackground(new java.awt.Color(255, 102, 102));
        GenPDFPuntoFyF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenPDFPuntoFyF.setText("PDF");
        GenPDFPuntoFyF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenPDFPuntoFyFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PunFlotanteLayout = new javax.swing.GroupLayout(PunFlotante);
        PunFlotante.setLayout(PunFlotanteLayout);
        PunFlotanteLayout.setHorizontalGroup(
            PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtResMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(txtPfloatHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResPfloatHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(txtPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtResSigno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(14, 14, 14)))
                                .addGap(220, 220, 220))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResValDeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17))
                            .addGroup(PunFlotanteLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResExBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(139, 139, 139)))
                        .addGap(131, 131, 131))))
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btPflota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(GenPDFPuntoFyF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(btLimPuntoFloat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PunFlotanteLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(cajaTxtPfijoYflota)))
                .addGap(185, 185, 185))
        );
        PunFlotanteLayout.setVerticalGroup(
            PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PunFlotanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(cajaTxtPfijoYflota, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPflota, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btLimPuntoFloat, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(GenPDFPuntoFyF, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(txtResSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(txtResExBin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtResMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PunFlotanteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtResValDeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel21))
                .addGap(12, 12, 12)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(txtResPfloatBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PunFlotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPfloatHexa, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtResPfloatHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        Unidad1.addTab("PUNTO FLOTANTE", PunFlotante);

        PropaErrores.setBackground(new java.awt.Color(204, 204, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("PROPAGACION DE ERRORES");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Ingresa el valor de \"X\":");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Ingresa el numero de iteraciones:");

        tableProErro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteracion", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProErro);

        btCalcularProErro.setText("CALCULAR");
        btCalcularProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularProErroActionPerformed(evt);
            }
        });

        btLimpiarProErro.setText("LIMPIAR");
        btLimpiarProErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarProErroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PropaErroresLayout = new javax.swing.GroupLayout(PropaErrores);
        PropaErrores.setLayout(PropaErroresLayout);
        PropaErroresLayout.setHorizontalGroup(
            PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropaErroresLayout.createSequentialGroup()
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                        .addGap(127, 127, 127))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaTxtValorProX)
                            .addComponent(cajaTxtNumIterPro, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(155, 155, 155))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btCalcularProErro, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(btLimpiarProErro, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addGap(155, 155, 155)))
                .addGap(69, 69, 69))
        );
        PropaErroresLayout.setVerticalGroup(
            PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropaErroresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropaErroresLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtValorProX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaTxtNumIterPro, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(PropaErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalcularProErro, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btLimpiarProErro, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        Unidad1.addTab("PROPAGACION ERRORES", PropaErrores);

        Bolzano.setBackground(new java.awt.Color(204, 255, 204));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Ingrese el extremo izquierdo del intervalo:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Ingrese el extremo derecho del intervalo:");

        cajaTxtInterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxtInterAActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("METODO DE BOLZANO");

        M_Bolzano.setBackground(new java.awt.Color(0, 204, 204));
        M_Bolzano.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_Bolzano.setText("INGRESAR DATOS");
        M_Bolzano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BolzanoActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Ingrese la función (utilice 'x' como variable):");

        cajaTxtFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxtFuncionActionPerformed(evt);
            }
        });

        FuncionXD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FuncionXD.setText("--");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("La aproximación de la solución es:");

        LimpiarMBolza.setBackground(new java.awt.Color(0, 204, 204));
        LimpiarMBolza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LimpiarMBolza.setText("LIMPIAR");
        LimpiarMBolza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarMBolzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BolzanoLayout = new javax.swing.GroupLayout(Bolzano);
        Bolzano.setLayout(BolzanoLayout);
        BolzanoLayout.setHorizontalGroup(
            BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)))
                .addGap(39, 39, 39)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addComponent(cajaTxtInterB)
                        .addGap(1, 1, 1))
                    .addComponent(cajaTxtInterA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaTxtFuncion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(101, 101, 101))
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(244, 244, 244))
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addComponent(M_Bolzano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LimpiarMBolza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(FuncionXD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(132, 132, 132))
        );
        BolzanoLayout.setVerticalGroup(
            BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BolzanoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtInterA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BolzanoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtInterB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_Bolzano, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(LimpiarMBolza, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(BolzanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(FuncionXD, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );

        Unidad1.addTab("BOLZANO", Bolzano);

        Biseccion.setBackground(new java.awt.Color(153, 255, 204));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Ingrese la función:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Ingrese el límite inferior del intervalo (a):");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Ingrese el límite superior del intervalo (b):");

        M_Biseccion.setBackground(new java.awt.Color(102, 204, 255));
        M_Biseccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_Biseccion.setText("CALCULAR");
        M_Biseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BiseccionActionPerformed(evt);
            }
        });

        Limpiar_MBisec.setBackground(new java.awt.Color(102, 204, 255));
        Limpiar_MBisec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Limpiar_MBisec.setText("LIMPIAR");
        Limpiar_MBisec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_MBisecActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("La raíz se encuentra en x = ");

        RespuestaMB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RespuestaMB.setText("Respuesta");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setText("METODO BISECCION");

        javax.swing.GroupLayout BiseccionLayout = new javax.swing.GroupLayout(Biseccion);
        Biseccion.setLayout(BiseccionLayout);
        BiseccionLayout.setHorizontalGroup(
            BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiseccionLayout.createSequentialGroup()
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(M_Biseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(Limpiar_MBisec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaTxtFB)
                                    .addComponent(cajaTxtBInteA)
                                    .addComponent(cajaTxtBInteB)))
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addGap(312, 312, 312))
                            .addGroup(BiseccionLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(162, 162, 162)))
                        .addGap(31, 31, 31)))
                .addGap(162, 162, 162))
            .addGroup(BiseccionLayout.createSequentialGroup()
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(RespuestaMB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(273, 273, 273))
        );
        BiseccionLayout.setVerticalGroup(
            BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiseccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtFB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtBInteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BiseccionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaTxtBInteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_Biseccion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Limpiar_MBisec, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(BiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RespuestaMB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147))
        );

        Unidad1.addTab("BISECCION", Biseccion);

        EspMetricos.setBackground(new java.awt.Color(255, 255, 204));

        CalcularEsMetricos.setText("CALCULAR");
        CalcularEsMetricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularEsMetricosActionPerformed(evt);
            }
        });

        Limpiar_Espacios.setText("LIMPIAR");
        Limpiar_Espacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_EspaciosActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("ESPACIOS METRICOS");

        cajaTxt_x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cajaTxt_y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cajaTxt_x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cajaTxt_y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTxt_y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTxt_y2ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Ingrese las coordenadas del primer punto:  (");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText(";");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText(")");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Ingrese las coordenadas del segundo punto: (");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText(";");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText(")");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("La distancia entre los dos puntos es:");

        Respuesta_Esp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Respuesta_Esp.setText("--");

        javax.swing.GroupLayout EspMetricosLayout = new javax.swing.GroupLayout(EspMetricos);
        EspMetricos.setLayout(EspMetricosLayout);
        EspMetricosLayout.setHorizontalGroup(
            EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspMetricosLayout.createSequentialGroup()
                .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(CalcularEsMetricos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(Limpiar_Espacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaTxt_x1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(cajaTxt_x2)
                        .addGap(10, 10, 10)
                        .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EspMetricosLayout.createSequentialGroup()
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaTxt_y2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addGroup(EspMetricosLayout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(cajaTxt_y1)))
                        .addGap(25, 25, 25)))
                .addGap(92, 92, 92))
            .addGroup(EspMetricosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta_Esp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(151, 151, 151))
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EspMetricosLayout.setVerticalGroup(
            EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspMetricosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(85, 85, 85)
                .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EspMetricosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cajaTxt_x1))
                            .addGroup(EspMetricosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cajaTxt_y2))
                            .addGroup(EspMetricosLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(25, 25, 25)))
                .addGap(7, 7, 7)
                .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addComponent(cajaTxt_x2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EspMetricosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cajaTxt_y1)
                        .addGap(9, 9, 9)))
                .addGap(31, 31, 31)
                .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalcularEsMetricos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(Limpiar_Espacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(165, 165, 165)
                .addGroup(EspMetricosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Respuesta_Esp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        Unidad1.addTab("ESPACIOS METRICOS", EspMetricos);

        javax.swing.GroupLayout SerieTylorLayout = new javax.swing.GroupLayout(SerieTylor);
        SerieTylor.setLayout(SerieTylorLayout);
        SerieTylorLayout.setHorizontalGroup(
            SerieTylorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        SerieTylorLayout.setVerticalGroup(
            SerieTylorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        Unidad1.addTab("SERIE DE TYLOR", SerieTylor);

        Unidades.addTab("UNIDAD 1", Unidad1);
        Unidades.addTab("UNIDAD 2", Unidad2);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Unidades)
                .addContainerGap())
            .addComponent(Titulo_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(Titulo_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Unidades)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btErrReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrReActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0, Ea = 0;
        err2 = Double.parseDouble(cajaTxtErrN2.getText());
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        Ea = Erro.errAbs(err1, err2);
        txtResEr.setText(String.valueOf(Erro.errRel(Ea, err2)));
    }//GEN-LAST:event_btErrReActionPerformed

    private void btErrAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErrAbsActionPerformed
        // TODO add your handling code here:
        double err1 = 0, err2 = 0;
        err1 = Double.parseDouble(cajaTxtErrN1.getText());
        err2 = Double.parseDouble(cajaTxtErrN2.getText());

        txtResEa.setText(String.valueOf(Erro.errAbs(err1, err2)));

    }//GEN-LAST:event_btErrAbsActionPerformed

    private void btLimErrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimErrActionPerformed
        // TODO add your handling code here:
        LimpiarErr();
    }//GEN-LAST:event_btLimErrActionPerformed

    private void btPflotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPflotaActionPerformed
        // TODO add your handling code here:
        String Pfloat = "";

        Pfloat = cajaTxtPfijoYflota.getText();
        boolean verdad = PuntoF.verficarHexa(Pfloat);

        if (verdad == true) {

            txtResPfloatBin.setVisible(false);
            txtResPfloatHexa.setVisible(false);
            txtPfloatBin.setVisible(false);
            txtPfloatHexa.setVisible(false);

            int PfloatEntero = Integer.parseInt(Pfloat.substring(2), 16);
            int signo = (PfloatEntero >> 31) & 1;
            int exponente = ((PfloatEntero >> 23) & 0xFF);
            int mantisa = PfloatEntero & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');

            double valor = Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23))) * Math.pow(2, exponente - 127);

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));

        } else {

            txtResPfloatBin.setVisible(true);
            txtResPfloatHexa.setVisible(true);
            txtPfloatBin.setVisible(true);
            txtPfloatHexa.setVisible(true);

            float ValDeci = 0f;
            ValDeci = Float.parseFloat(cajaTxtPfijoYflota.getText());

            int bits = Float.floatToIntBits(ValDeci);
            int signo = (bits >> 31) & 1;
            int exponente = (bits >> 23) & 0xFF;
            int mantisa = bits & 0x7FFFFF;

            String mantisaBinaria = String.format("%23s", Integer.toBinaryString(mantisa)).replace(' ', '0');
            String exponenteBinario = String.format("%8s", Integer.toBinaryString(exponente)).replace(' ', '0');
            String valorBinario = String.format("%32s", Integer.toBinaryString(bits)).replace(' ', '0');
            String valorHexa = String.format("%8s", Integer.toHexString(bits)).replace(' ', '0').toUpperCase();

            float valor = (float) ((Math.pow(-1, signo) * (1 + (mantisa / Math.pow(2, 23)))) * Math.pow(2, exponente - 127));

            txtResSigno.setText(String.valueOf(signo));
            txtResExBin.setText(String.valueOf(exponenteBinario));
            txtResMan.setText(String.valueOf(mantisaBinaria));
            txtResValDeci.setText(String.valueOf(valor));
            txtResPfloatBin.setText(String.valueOf(valorBinario));
            txtResPfloatHexa.setText(String.valueOf("0X" + valorHexa));
        }


    }//GEN-LAST:event_btPflotaActionPerformed

    private void btLimPuntoFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimPuntoFloatActionPerformed
        // TODO add your handling code here:
        LimpiarPuntoFlotante();
    }//GEN-LAST:event_btLimPuntoFloatActionPerformed

    private void btCalcularProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularProErroActionPerformed
        // TODO add your handling code here:
        try {
            modelo = (DefaultTableModel) this.tableProErro.getModel();

            String valXproErro = cajaTxtValorProX.getText();
            BigDecimal valBigPro = new BigDecimal(valXproErro);
            int IterProErro = Integer.parseInt(cajaTxtNumIterPro.getText());

            XYDataset data = proErro.createDataset(valBigPro, IterProErro);
            JFreeChart chart = proErro.createChart(data);

            ChartFrame frame = new ChartFrame("PROPAGACION DE ERRORES", chart);
            frame.pack();
            frame.setVisible(true);
            //tabla
            for (int i = 1; i <= IterProErro; i++) {
                BigDecimal numerator = proErro.exp(valBigPro, i);
                BigDecimal denominator = proErro.exp(valBigPro, i).subtract(BigDecimal.ONE);
                BigDecimal result = numerator.divide(denominator, 128, RoundingMode.HALF_UP);

                Object datosProErro[] = new Object[]{i, result.toString()};
                modelo.addRow(datosProErro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO HAY DATOS EN EL PROGRAMA");
        }

    }//GEN-LAST:event_btCalcularProErroActionPerformed

    private void btLimpiarProErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarProErroActionPerformed
        // TODO add your handling code here:
        cajaTxtNumIterPro.setText("");
        cajaTxtValorProX.setText("");
        modelo.getDataVector().removeAllElements();
        tableProErro.updateUI();
    }//GEN-LAST:event_btLimpiarProErroActionPerformed

    private void M_BiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BiseccionActionPerformed
        // TODO add your handling code here:
        double InterB_A = Double.parseDouble(cajaTxtBInteA.getText());
        double InterB_B = Double.parseDouble(cajaTxtBInteB.getText());
        String functionStr = cajaTxtFB.getText();

        Function<Double, Double> funcionB;
        funcionB = Bisec.CrearFuncionBis(functionStr);
        double xD = Bisec.findRoot(InterB_A, InterB_B, funcionB);
        Bisec.evaluarFuncion(functionStr, xD);
        RespuestaMB.setText(String.valueOf(Bisec.findRoot(InterB_A, InterB_B, funcionB)));
        Bisec.solveBisection(InterB_A, InterB_B, funcionB);
        Graf.generarGrafica(functionStr, InterB_A, InterB_B);
        Bisec.mostrarGrafica(functionStr,InterB_A, InterB_B, funcionB);
    }//GEN-LAST:event_M_BiseccionActionPerformed

    private void Limpiar_MBisecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_MBisecActionPerformed
        // TODO add your handling code here:
        LimpiarBiseccion();
    }//GEN-LAST:event_Limpiar_MBisecActionPerformed

    private void cajaTxtInterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxtInterAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxtInterAActionPerformed

    private void M_BolzanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BolzanoActionPerformed
        // TODO add your handling code here:
        double InterA = Double.parseDouble(cajaTxtInterA.getText());
        double InterB = Double.parseDouble(cajaTxtInterB.getText());
        String funcionString = cajaTxtFuncion.getText();

        Function<Double, Double> funcion;
        funcion = Bolza.CrearFuncion(funcionString);

        double valorX = Bolza.EncontrarAproximacion(funcion, InterA, InterB);
        Bolza.EvaluarFuncion(funcionString,valorX);
        Graf.generarGrafica(funcionString, InterA, InterB);
        FuncionXD.setText(String.valueOf(Bolza.EncontrarAproximacion(funcion, InterA, InterB)));
    }//GEN-LAST:event_M_BolzanoActionPerformed

    private void LimpiarMBolzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarMBolzaActionPerformed
        // TODO add your handling code here:
        LimpiarBolzano();
    }//GEN-LAST:event_LimpiarMBolzaActionPerformed

    private void cajaTxtFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxtFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxtFuncionActionPerformed

    private void CalcularEsMetricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularEsMetricosActionPerformed
        // TODO add your handling code here:
        double x1 = Double.parseDouble(cajaTxt_x1.getText());
        double y1 = Double.parseDouble(cajaTxt_y1.getText());
        double x2 = Double.parseDouble(cajaTxt_x2.getText());
        double y2 = Double.parseDouble(cajaTxt_y2.getText());
        Respuesta_Esp.setText(String.valueOf(Esp.calcularDistancia(x1, y1, x2, y2)));
        Esp.generarGrafico(x1, y1, x2, y2);

    }//GEN-LAST:event_CalcularEsMetricosActionPerformed

    private void cajaTxt_y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTxt_y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTxt_y2ActionPerformed

    private void Limpiar_EspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_EspaciosActionPerformed
        // TODO add your handling code here:
        LimpiarEspMetricos();
    }//GEN-LAST:event_Limpiar_EspaciosActionPerformed

    private void GenPDFPuntoFyFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenPDFPuntoFyFActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog("Ingresa el nombre del nuevo archivo");
            generar.generar(nombre, cajaTxtPfijoYflota.getText(), txtResSigno.getText(), txtResExBin.getText(), txtResMan.getText(), txtResValDeci.getText());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_GenPDFPuntoFyFActionPerformed

    private void ComboBox_CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CWActionPerformed

    private void ComboBox_CTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String d ="decimal", b ="binario", h ="hexadecimal", o ="octal";
        String tipo1=(String)ComboBox_CW.getSelectedItem();
        String tipo2=(String)ComboBox_CT.getSelectedItem();
        String numero1 = cajaTxt_CW.getText();
        
        if ( tipo1.equalsIgnoreCase(d)) {
            int number = Integer.parseInt(numero1);
            if ( tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToBinary(number)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToHexadecimal(number)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.decimalToOctal(number)));
            } else if (tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(b)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToHexadecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.binaryToOctal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(h)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToBinary(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)) {
                labelTxtResConv.setText(String.valueOf(Conver.hexadecimalToOctal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)){
                labelTxtResConv.setText(numero1);
            }
        } else if (tipo1.equalsIgnoreCase(o)){
            if ( tipo2.equalsIgnoreCase(d)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToDecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(h)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToHexadecimal(numero1)));
            } else if (tipo2.equalsIgnoreCase(b)) {
                labelTxtResConv.setText(String.valueOf(Conver.octalToBinary(numero1)));
            } else if (tipo2.equalsIgnoreCase(o)){
                labelTxtResConv.setText(numero1);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LimpiarConver();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Biseccion;
    private javax.swing.JPanel Bolzano;
    private javax.swing.JButton CalcularEsMetricos;
    private javax.swing.JComboBox<String> ComboBox_CT;
    private javax.swing.JComboBox<String> ComboBox_CW;
    private javax.swing.JPanel Conversiones;
    private javax.swing.JPanel EspMetricos;
    private javax.swing.JLabel FuncionXD;
    private javax.swing.JButton GenPDFPuntoFyF;
    private javax.swing.JButton LimpiarMBolza;
    private javax.swing.JButton Limpiar_Espacios;
    private javax.swing.JButton Limpiar_MBisec;
    private javax.swing.JButton M_Biseccion;
    private javax.swing.JButton M_Bolzano;
    private javax.swing.JPanel PanErrores;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PropaErrores;
    private javax.swing.JPanel PunFlotante;
    private javax.swing.JLabel RespuestaMB;
    private javax.swing.JLabel Respuesta_Esp;
    private javax.swing.JPanel SerieTylor;
    private javax.swing.JLabel Titulo_Principal;
    private javax.swing.JTabbedPane Unidad1;
    private javax.swing.JTabbedPane Unidad2;
    private javax.swing.JTabbedPane Unidades;
    private javax.swing.JButton btCalcularProErro;
    private javax.swing.JButton btErrAbs;
    private javax.swing.JButton btErrRe;
    private javax.swing.JButton btLimErr;
    private javax.swing.JButton btLimPuntoFloat;
    private javax.swing.JButton btLimpiarProErro;
    private javax.swing.JButton btPflota;
    private javax.swing.JTextField cajaTxtBInteA;
    private javax.swing.JTextField cajaTxtBInteB;
    private javax.swing.JTextField cajaTxtErrN1;
    private javax.swing.JTextField cajaTxtErrN2;
    private javax.swing.JTextField cajaTxtFB;
    private javax.swing.JTextField cajaTxtFuncion;
    private javax.swing.JTextField cajaTxtInterA;
    private javax.swing.JTextField cajaTxtInterB;
    private javax.swing.JTextField cajaTxtNumIterPro;
    private javax.swing.JTextField cajaTxtPfijoYflota;
    private javax.swing.JTextField cajaTxtValorProX;
    private javax.swing.JTextField cajaTxt_CW;
    private javax.swing.JTextField cajaTxt_x1;
    private javax.swing.JTextField cajaTxt_x2;
    private javax.swing.JTextField cajaTxt_y1;
    private javax.swing.JTextField cajaTxt_y2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTxtResConv;
    private javax.swing.JTable tableProErro;
    private javax.swing.JLabel txtPfloatBin;
    private javax.swing.JLabel txtPfloatHexa;
    private javax.swing.JLabel txtResEa;
    private javax.swing.JLabel txtResEr;
    private javax.swing.JLabel txtResExBin;
    private javax.swing.JLabel txtResMan;
    private javax.swing.JLabel txtResPfloatBin;
    private javax.swing.JLabel txtResPfloatHexa;
    private javax.swing.JLabel txtResSigno;
    private javax.swing.JLabel txtResValDeci;
    // End of variables declaration//GEN-END:variables

    private void LimpiarConver() {
        cajaTxt_CW.setText("");
        labelTxtResConv.setText("--");
    }

    private void LimpiarErr() {
        txtResEa.setText("--");
        txtResEr.setText("--");
        cajaTxtErrN1.setText("");
        cajaTxtErrN2.setText("");
    }

    private void LimpiarPuntoFlotante() {
        txtResPfloatBin.setVisible(false);
        txtResPfloatHexa.setVisible(false);
        txtPfloatBin.setVisible(false);
        txtPfloatHexa.setVisible(false);
        txtResSigno.setText("--");
        txtResExBin.setText("--");
        txtResMan.setText("--");
        txtResValDeci.setText("--");
        txtResPfloatBin.setText("--");
        txtResPfloatHexa.setText("--");
        cajaTxtPfijoYflota.setText("");
    }
    private void LimpiarBiseccion() {
        cajaTxtFB.setText("");
        cajaTxtBInteA.setText("");
        cajaTxtBInteB.setText("");
        RespuestaMB.setText("--");
    }
    
    private void LimpiarBolzano() {
        cajaTxtFuncion.setText("");
        cajaTxtInterA.setText("");
        cajaTxtInterB.setText("");
        FuncionXD.setText("--");
    }
    
    private void LimpiarEspMetricos() {
        cajaTxt_x1.setText("");
        cajaTxt_y1.setText("");
        cajaTxt_x2.setText("");
        cajaTxt_y2.setText("");
        Respuesta_Esp.setText("--");
    }
}
